#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("VaxineApp.Droid.Resource", IsApplication=true)]

namespace VaxineApp.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int accent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorAccent = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimary = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int colorPrimaryDark = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int launcher_background = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int primary = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int primaryDark = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int splash_background = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int window_background = 2130771976;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int AbdulBasir = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int AppIcon = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int FlyoutHeader_Account = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int FlyoutItem_AboutUs = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int FlyoutItem_Help = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int FlyoutItem_Home = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int FlyoutItem_settings = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int FlyoutMenuItem_Logout = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int Home_Area = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int Home_Family = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int Home_Insights = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int Home_Profile = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int Home_Registration = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int Home_Status = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int MohammadYaseen = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int NaveedAhmed = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int NotificationsIcon = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int ProfilePhoto = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int SaeedaRasuly = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int SavePDF = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int Search = 2130837524;
			
			// aapt resource value: 0x7F020019
			public const int splash_logo = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int splash_screen = 2130837530;
			
			// aapt resource value: 0x7F020015
			public const int ToolbarItem_Notifications = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int ToolbarItem_Search = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int ToolbarItem_Share = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int Universal_Edit = 2130837528;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int buttonHello = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int buttonHi = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int textView1 = 2130903042;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int my_widget = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int icon = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int icon_round = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int launcher_foreground = 2131034114;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060002
			public const int admob_id = 2131099650;
			
			// aapt resource value: 0x7F060000
			public const int ApplicationName = 2131099648;
			
			// aapt resource value: 0x7F060003
			public const int banner_ad_unit_id = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int drawer_close = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int drawer_open = 2131099653;
			
			// aapt resource value: 0x7F060001
			public const int Hello = 2131099649;
			
			// aapt resource value: 0x7F060006
			public const int menu_refresh = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int monkey_ipsum = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int tile_name = 2131099656;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F070000
			public const int MainTheme = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int MyTheme = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int MyTheme_Base = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int MyTheme_Splash = 2131165187;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F080000
			public const int my_widget_provider = 2131230720;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
